---
title: "hw-01"
author: "Adrian Maroto-Andresen (S2570928)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

```{r load-data, message=FALSE}
edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
 var_w_na<-(select(edibnb, id:listing_url))
arrange(edibnb, !is.na(var_w_na))
```


```{r hw1-ex1.1}
best<- select(edibnb, id,review_scores_rating, number_of_reviews)
  best2<- filter(best, review_scores_rating>=100)
  arrange(best2,desc(number_of_reviews))
```

variables with missing observations: price, neighbourhood and review scores rating.And the ID of the listing that has the highest number of reviews with a perfect review score of 100% is:860170
------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
OT_prop <- select (edibnb, neighbourhood, price)
OT_prop2 <- filter(OT_prop,price>=100)
  count(OT_prop2,neighbourhood="Old Town",sort=TRUE)

```

```{r hw1-ex2.1}
Sside_prop <-filter(edibnb,neighbourhood=="Southside" & accommodates >= 4)
Sside_prop2 <-summarise(Sside_prop, mean=mean(price,na.rm=TRUE), max=max(price,na.rm=TRUE),min=min(price,na.rm=TRUE))
arrange(Sside_prop2, desc(max))
```




## EXERCISE 3

```{r hw1-ex3}
# remove this comment and add the code for Exercise 3 here

```


_Remove this text, and add your answer for Exercise 3 here._



------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
# remove this comment and add the code for Exercise 4 here

```


_Remove this text, and add your answer for Exercise 4 here._


------------------------------------------------------------------------------
